### ISSUE TITLE
Endless loop on Windows

### ISSUE THREAD

**Issue by ihupoo** [aleclarson/find-dependency#2]
I encountered this problem when using `vite-plugin-mdx` . When start dev , the web page network which downloading the mdx file is always  pending

I debug and find that is because the homePath is `C:\Users\xxxx` and the dir is `D:\`

They will never match
```js
const homePath = require('os').homedir()
...
while ((dir = dirname(dir)) != homePath) {
    dep = getDir(join(dir, 'node_modules', name))
    if (dep) return dep
}
```

Only on Windows would meet this problem。I don't know how to fix it ...

**Comment by aleclarson** [comment]
Fixed in v1.3.1 👍
